# Generated by Django 2.0.1 on 2018-05-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('views_student_list', '查看学员信息表'), ('views_student_info', '查看学员详细信息'), ('views_users', '查看用户信息')), 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
    ]
